[project]
name = "minesweeper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.10.2",
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]
